### PR TITLE
Use public_web website folder (e.g. built) for imserver jsonpath because /website is never updated

### PR DESCRIPTION
**Pull request by ineffyble**

### CODE REVIEW

**Review by AlexCPU — APPROVED** [review]
Yep, that's a good point.  We might have missed a portal update based on how old that content is...  Oh well, this'll fix it when it deploys.

**Comment by ineffyble** [comment]
> Yep, that's a good point. We might have missed a portal update based on how old that content is... Oh well, this'll fix it when it deploys.

I don't think we did miss a portal update, or we'd have had more complaints.

**Comment by AlexCPU** [comment]
> I don't think we did miss a portal update, or we'd have had more complaints.

I didn't think so, but the files in `static` were dated August last year, and I thought the portal update was more recent than that.

**Comment by ineffyble** [comment]
@AlexCPU Ah, but the update in November probably only included crew released before August, so we snuck by.

**Pull request merged**
